/**
 * Gravity block visual recovery layer.
 *
 * Selector-based around the official block renderer BEM classes. It prevents new
 * renderer variants from appearing as raw/unstyled HTML when a design family or
 * masterclass does not provide a dedicated rule yet.
 */
export const BLOCK_VISUAL_RECOVERY_CSS = `
/* === Gravity Block Visual Recovery v1 === */
:root { --block-recovery-card-bg: var(--surface, #ffffff); --block-recovery-ink: var(--text, #0f172a); --block-recovery-muted: var(--muted, #475569); --block-recovery-border: var(--border, rgba(148, 163, 184, .16)); --block-recovery-soft: 0 10px 28px rgba(15, 23, 42, .055); --block-recovery-lift: 0 18px 42px rgba(15, 23, 42, .09); }
.block-section__inner,.section-shell{width:100%;min-width:0}.shell-panel,.shell-comparison,.shell-band,.shell-plain{position:relative}.shell-panel,.shell-comparison{padding:clamp(1.25rem,3vw,2.15rem);border-radius:clamp(1.2rem,2.4vw,1.8rem);background:linear-gradient(180deg,rgba(255,255,255,.96),rgba(248,250,252,.9));border:1px solid var(--block-recovery-border);box-shadow:var(--block-recovery-soft)}
.section-tone-base{background:var(--bg,#f8fafc)}.section-tone-soft{background:linear-gradient(180deg,rgba(var(--primary-rgb,15,118,110),.035),rgba(255,255,255,0))}.section-tone-alt{background:color-mix(in srgb,var(--bg,#f8fafc) 82%,var(--surface,#fff) 18%)}.section-tone-contrast{background:radial-gradient(circle at 80% 0%,rgba(var(--primary-rgb,15,118,110),.08),transparent 30%),var(--bg,#f8fafc)}
.block__subtitle,.editorial-lead,.block__header p{color:var(--block-recovery-muted);font-size:clamp(1.02rem,1.45vw,1.16rem);max-width:68ch}.block__cta-group{display:flex;align-items:center;gap:.85rem;flex-wrap:wrap;margin-top:clamp(1.1rem,2vw,1.65rem)}.block__cta-note,.block__cta-phone{display:inline-flex;align-items:center;min-height:2.75rem;max-width:54ch;padding:.72rem .95rem;border-radius:.95rem;background:rgba(15,23,42,.035);border:1px solid var(--block-recovery-border);color:var(--block-recovery-muted);font-size:.92rem;line-height:1.35}.cta-primary.large{min-height:3.45rem;padding-inline:1.35rem;font-size:1.03rem}.cta-primary__icon,.cta-primary__text{display:inline-flex;align-items:center}
.block__pills,.services-grid__trust,.urgency-banner__pills,.map-block__pills,.price-guidance__bullets,.process-steps__bullets,.cta-panel__bullets{display:flex;flex-wrap:wrap;gap:.55rem;list-style:none;margin:1rem 0 0;padding:0}.block__pill,.services-grid__trust .block__pill,.urgency-banner__pills .block__pill{display:inline-flex;align-items:center;min-height:2.15rem;padding:.48rem .78rem;border-radius:999px;background:rgba(var(--primary-rgb,15,118,110),.075);border:1px solid rgba(var(--primary-rgb,15,118,110),.14);color:color-mix(in srgb,var(--primary,#0f766e) 82%,var(--text,#0f172a) 18%);font-weight:850;font-size:.83rem;line-height:1.2}
.brand,.nav__link,.nav-mobile__link,.footer__nav-link,.footer__link{text-decoration:none}.brand{color:var(--text,#0f172a);font-weight:950;letter-spacing:-.02em}.nav__links-group,.nav-mobile__links{display:flex;align-items:center;gap:.35rem;flex-wrap:wrap}.nav__link,.nav-mobile__link{display:inline-flex;align-items:center;min-height:2.55rem;padding:.62rem .84rem;border-radius:999px;color:var(--text,#0f172a);font-weight:800}.nav__link:hover,.nav__link.is-active,.nav-mobile__link:hover{background:rgba(15,23,42,.055)}.nav-mobile__summary{cursor:pointer;list-style:none;display:inline-flex;align-items:center;justify-content:center;min-height:2.65rem;padding:0 .95rem;border-radius:999px;background:var(--surface,#fff);border:1px solid var(--block-recovery-border);color:var(--text,#0f172a);font-weight:900}.nav-mobile__summary::-webkit-details-marker{display:none}.nav-mobile__panel{position:absolute;right:1rem;margin-top:.75rem;width:min(22rem,calc(100vw - 2rem));padding:.9rem;border-radius:1.15rem;background:var(--surface,#fff);border:1px solid var(--block-recovery-border);box-shadow:var(--block-recovery-lift);z-index:100}
.hero-disposition-left{isolation:isolate}.hero--proof_first .hero__minimal,.hero__centered--with-media{display:grid;grid-template-columns:minmax(0,.92fr) minmax(310px,.72fr);gap:clamp(1.4rem,3.5vw,3rem);align-items:center;max-width:1180px}.hero--proof_first .hero__eyebrow,.hero__eyebrow{width:max-content;max-width:100%}.hero--proof_first h1,.hero--proof_first .hero__subtitle,.hero--proof_first .cta-row{grid-column:1}.hero--proof_first .hero-visual{grid-column:2;grid-row:1 / span 4;margin:0}.hero-visual__frame{overflow:hidden;border-radius:clamp(1.25rem,2.4vw,2rem);border:1px solid rgba(255,255,255,.75);box-shadow:var(--block-recovery-lift);aspect-ratio:1.24 / 1}.hero-visual__frame img{width:100%;height:100%;object-fit:cover;display:block}
.service-card__meta,.step-card__meta,.step-row__meta,.proof-row__meta,.price-card__facts{display:flex;flex-wrap:wrap;gap:.45rem;margin:.85rem 0 0;padding:0;list-style:none}.service-card__meta li,.step-card__meta li,.step-row__meta li,.proof-row__meta li,.price-card__facts li,.process-steps__bullets li,.price-guidance__bullets li,.cta-panel__bullets li{display:inline-flex;align-items:center;padding:.42rem .62rem;border-radius:.7rem;background:rgba(15,23,42,.04);border:1px solid rgba(148,163,184,.12);color:var(--block-recovery-muted);font-size:.86rem;line-height:1.25}
.services-grid--magazine .services-grid__magazine,.services-grid__magazine{display:grid;grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);gap:clamp(1.25rem,2.8vw,2.4rem);align-items:start}.services-grid__magazine-lead,.services-grid__magazine-stack,.services-grid__cards{display:grid;gap:1rem;min-width:0}.services-grid__intro,.faq-block__intro,.trust-band__intro,.process-steps__intro,.local-proof__intro,.price-guidance__intro,.map-block__intro,.urgency-layout__intro{display:grid;gap:.75rem;color:var(--block-recovery-muted)}.services-grid__magazine-feature,.service-card,.proof-card,.step-card,.price-card,.faq-item,.faq-entry,.testimonial-card,.trust-band__signal-card,.proof-row,.map-block__support,.cta-panel__consult-card{min-width:0;border-radius:clamp(1rem,2vw,1.35rem);background:var(--block-recovery-card-bg);border:1px solid var(--block-recovery-border);box-shadow:var(--block-recovery-soft);padding:clamp(1.1rem,2vw,1.45rem)}.services-grid__magazine-feature{background:linear-gradient(180deg,rgba(var(--primary-rgb,15,118,110),.055),rgba(255,255,255,.98))}
.process-steps--rail .process-steps__rail-layout,.process-steps__rail-layout,.local-proof--coverage .local-proof__coverage,.local-proof__coverage,.price-guidance--insight .price-guidance__insight,.price-guidance__insight,.cta-panel--consult .cta-panel__consult,.cta-panel__consult,.map-block--context-frame .map-block__context,.map-block__context{display:grid;grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);gap:clamp(1.25rem,3vw,2.4rem);align-items:start}.process-steps__rail-copy,.local-proof__coverage-copy,.price-guidance__insight-copy,.price-guidance__insight-panels,.cta-panel__consult-copy,.map-block__context-copy,.local-proof__coverage-cards{display:grid;gap:1rem;min-width:0}.process-steps__rail{position:relative;display:grid;gap:1rem;min-width:0}.process-step-rail{display:grid;grid-template-columns:auto minmax(0,1fr);gap:.9rem;align-items:start}.process-step-rail__index,.step-card__index,.local-proof__signal-index,.trust-band__signal-index,.proof-row__ordinal{display:inline-grid;place-items:center;width:2.75rem;height:2.75rem;border-radius:999px;background:linear-gradient(135deg,var(--primary,#0f766e),color-mix(in srgb,var(--primary,#0f766e),#000 18%));color:var(--text-on-primary,#fff);font-weight:950;box-shadow:0 10px 22px rgba(var(--primary-rgb,15,118,110),.18);flex:0 0 auto}.process-step-rail__body{min-width:0}.process-step-rail__body h3,.proof-row h3,.trust-band__signal-copy h3{margin-top:0;margin-bottom:.5rem}
.local-proof__signal-list,.trust-band__signal-grid,.local-proof__minimal-grid,.local-proof__grid,.process-steps__grid,.price-guidance__cards,.testimonials-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,15.5rem),1fr));gap:1rem;min-width:0}.local-proof__signal,.trust-band__signal-card{display:grid;grid-template-columns:auto minmax(0,1fr);gap:.85rem;align-items:start}.local-proof__signal-copy,.trust-band__signal-copy{display:grid;gap:.28rem;min-width:0}.local-proof__signal-copy strong{color:var(--block-recovery-ink);line-height:1.2}.local-proof__signal-copy span,.trust-band__signal-copy p,.proof-row p{color:var(--block-recovery-muted)}.proof-row--stacked{display:grid;grid-template-columns:auto minmax(0,1fr);gap:.9rem}.proof-card-minimal{border-radius:1.2rem;background:var(--surface,#fff);border:1px solid var(--block-recovery-border);box-shadow:var(--block-recovery-soft);padding:1.2rem}
.faq-block__accordion,.faq-block__accordion--refined{display:grid;gap:.85rem}.faq-summary-refined{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:.85rem;align-items:center;cursor:pointer;list-style:none;font-weight:850;color:var(--text,#0f172a)}.faq-summary-refined::-webkit-details-marker{display:none}.faq-summary-refined::after{content:'+';font-weight:950;color:var(--primary,#0f766e)}details[open]>.faq-summary-refined::after{content:'–'}.faq-content-refined{padding-top:.25rem;color:var(--block-recovery-muted)}
.urgency-banner--command,.urgency-banner{display:grid;grid-template-columns:minmax(0,1fr) minmax(130px,.26fr) auto;gap:1rem;align-items:center;border-radius:clamp(1.15rem,2.2vw,1.7rem);border:1px solid rgba(var(--primary-rgb,15,118,110),.16);padding:clamp(1.15rem,2.4vw,1.8rem);overflow:hidden}.urgency-banner__rail{position:absolute;inset:0 auto 0 0;width:.34rem;background:var(--primary,#0f766e)}.urgency-banner__content{min-width:0}.urgency-banner__status{display:inline-flex;width:max-content;max-width:100%;padding:.35rem .65rem;border-radius:999px;background:rgba(var(--primary-rgb,15,118,110),.09);color:var(--primary,#0f766e);font-size:.75rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase;margin-bottom:.75rem}.urgency-banner__statbox{display:grid;justify-items:center;gap:.1rem;padding:1rem;border-radius:1.1rem;background:rgba(255,255,255,.78);border:1px solid var(--block-recovery-border)}.urgency-banner__statlabel,.urgency-banner__statnote{color:var(--block-recovery-muted);font-size:.78rem;font-weight:800}.urgency-banner__statvalue{color:var(--primary,#0f766e);font-size:1.55rem;line-height:1}.urgency-banner__cta{justify-self:end}
.map-block__frame,.map-block__frame--context,.map-block__frame--boxed,.map-wrapper,.map-boxed-wrapper,.map-directory__visual{position:relative;min-height:clamp(320px,42vw,460px);overflow:hidden;border-radius:clamp(1.15rem,2.2vw,1.65rem);background:#e2e8f0;border:1px solid rgba(var(--primary-rgb,15,118,110),.16);box-shadow:var(--block-recovery-soft)}.map-block__iframe,.map-iframe,iframe.map-iframe{display:block;width:100%;height:100%;min-height:inherit;border:0}.map-block__overlay{position:absolute;left:1rem;right:1rem;bottom:1rem;display:flex;align-items:center;justify-content:space-between;gap:.75rem;pointer-events:none}.map-block__overlay-badge,.map-block__overlay-city{display:inline-flex;align-items:center;min-height:2.3rem;padding:.52rem .78rem;border-radius:999px;background:rgba(255,255,255,.94);border:1px solid rgba(255,255,255,.75);color:var(--text,#0f172a);font-weight:900;box-shadow:0 8px 20px rgba(15,23,42,.12)}.map-block__actions{display:flex;flex-wrap:wrap;gap:.75rem;margin-top:1rem}.map-block__note{color:var(--block-recovery-muted)}
.cta-panel__consult-card,.section-cta--terminal,.cta-panel__banner{border:1px solid rgba(var(--primary-rgb,15,118,110),.16);background:radial-gradient(circle at 100% 0%,rgba(var(--primary-rgb,15,118,110),.08),transparent 32%),var(--surface,#fff)}.footer-editorial{padding:clamp(2.2rem,5vw,4rem) 0}.footer__grid-refined,.footer__links-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,13rem),1fr));gap:1.4rem}.footer__block,.footer__brand-block,.footer__contact-details{display:grid;gap:.55rem}.footer__nav-list{display:grid;gap:.45rem;list-style:none;padding:0;margin:0}.footer__brand-name{font-weight:950}.footer__text,.footer__subtitle,.footer__link{color:var(--footer-muted,#cbd5e1)}
@media (max-width:900px){.hero--proof_first .hero__minimal,.hero__centered--with-media,.services-grid__magazine,.process-steps__rail-layout,.local-proof__coverage,.price-guidance__insight,.cta-panel__consult,.map-block__context,.urgency-banner--command,.urgency-banner{grid-template-columns:minmax(0,1fr)!important}.hero--proof_first h1,.hero--proof_first .hero__subtitle,.hero--proof_first .cta-row,.hero--proof_first .hero-visual{grid-column:auto;grid-row:auto}.urgency-banner__cta{justify-self:stretch}}@media (max-width:640px){.shell-panel,.shell-comparison{padding:1rem}.block__cta-group,.map-block__overlay{align-items:stretch;flex-direction:column}.block__cta-note,.block__cta-phone{width:100%;max-width:100%}.process-step-rail,.local-proof__signal,.trust-band__signal-card,.proof-row--stacked{grid-template-columns:minmax(0,1fr)}.process-step-rail__index,.step-card__index,.local-proof__signal-index,.trust-band__signal-index,.proof-row__ordinal{width:2.35rem;height:2.35rem}}
`;
