import type { LayoutRecipe } from './types.js';

export const ComparisonTable_RECIPES: LayoutRecipe[] = [
  {
    id: 'comparisonTable-compact',
    blockType: 'comparisonTable',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'compact',
    className: 'pfb pfb-comparisonTable pfb--editorial pfb--compact pfb--premium pfb-comparisonTable--compact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'comparisonTable-cards',
    blockType: 'comparisonTable',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'cards',
    className: 'pfb pfb-comparisonTable pfb--cards pfb--balanced pfb--practical pfb-comparisonTable--cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'comparisonTable-table-pro',
    blockType: 'comparisonTable',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'table',
    className: 'pfb pfb-comparisonTable pfb--split pfb--deep pfb--urgent pfb-comparisonTable--table-pro',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'comparisonTable-pros-cons',
    blockType: 'comparisonTable',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'pros',
    className: 'pfb pfb-comparisonTable pfb--timeline pfb--dense pfb--local pfb-comparisonTable--pros-cons',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'comparisonTable-decision-matrix',
    blockType: 'comparisonTable',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'decision',
    className: 'pfb pfb-comparisonTable pfb--compact pfb--compact pfb--technical pfb-comparisonTable--decision-matrix',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'comparisonTable-cheap-vs-quality',
    blockType: 'comparisonTable',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'cheap',
    className: 'pfb pfb-comparisonTable pfb--contrast pfb--balanced pfb--trust pfb-comparisonTable--cheap-vs-quality',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'comparisonTable-urgent-vs-planned',
    blockType: 'comparisonTable',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'urgent',
    className: 'pfb pfb-comparisonTable pfb--magazine pfb--deep pfb--premium pfb-comparisonTable--urgent-vs-planned',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'comparisonTable-repair-vs-replace',
    blockType: 'comparisonTable',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'repair',
    className: 'pfb pfb-comparisonTable pfb--masonry pfb--dense pfb--practical pfb-comparisonTable--repair-vs-replace',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'comparisonTable-materials-compare',
    blockType: 'comparisonTable',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'materials',
    className: 'pfb pfb-comparisonTable pfb--rail pfb--compact pfb--urgent pfb-comparisonTable--materials-compare',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'comparisonTable-local-options',
    blockType: 'comparisonTable',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'local',
    className: 'pfb pfb-comparisonTable pfb--matrix pfb--balanced pfb--local pfb-comparisonTable--local-options',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'comparisonTable-provider-compare',
    blockType: 'comparisonTable',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'provider',
    className: 'pfb pfb-comparisonTable pfb--accordion pfb--deep pfb--technical pfb-comparisonTable--provider-compare',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'comparisonTable-budget-compare',
    blockType: 'comparisonTable',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'budget',
    className: 'pfb pfb-comparisonTable pfb--spotlight pfb--dense pfb--trust pfb-comparisonTable--budget-compare',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'comparisonTable-risk-compare',
    blockType: 'comparisonTable',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'risk',
    className: 'pfb pfb-comparisonTable pfb--editorial pfb--compact pfb--premium pfb-comparisonTable--risk-compare',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'comparisonTable-timeline-compare',
    blockType: 'comparisonTable',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'timeline',
    className: 'pfb pfb-comparisonTable pfb--cards pfb--balanced pfb--practical pfb-comparisonTable--timeline-compare',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'comparisonTable-warranty-compare',
    blockType: 'comparisonTable',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'warranty',
    className: 'pfb pfb-comparisonTable pfb--split pfb--deep pfb--urgent pfb-comparisonTable--warranty-compare',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'comparisonTable-maintenance-compare',
    blockType: 'comparisonTable',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'maintenance',
    className: 'pfb pfb-comparisonTable pfb--timeline pfb--dense pfb--local pfb-comparisonTable--maintenance-compare',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'comparisonTable-premium-compare',
    blockType: 'comparisonTable',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'premium',
    className: 'pfb pfb-comparisonTable pfb--compact pfb--compact pfb--technical pfb-comparisonTable--premium-compare',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'comparisonTable-simple-chooser',
    blockType: 'comparisonTable',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'simple',
    className: 'pfb pfb-comparisonTable pfb--contrast pfb--balanced pfb--trust pfb-comparisonTable--simple-chooser',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
