import type { LayoutRecipe } from './types.js';

export const Content_RECIPES: LayoutRecipe[] = [
  {
    id: 'content-editorial',
    blockType: 'content',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'editorial',
    className: 'pfb pfb-content pfb--editorial pfb--compact pfb--premium pfb-content--editorial',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'content-cards',
    blockType: 'content',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'cards',
    className: 'pfb pfb-content pfb--cards pfb--balanced pfb--practical pfb-content--cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'content-split',
    blockType: 'content',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'split',
    className: 'pfb pfb-content pfb--split pfb--deep pfb--urgent pfb-content--split',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'content-guide',
    blockType: 'content',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'guide',
    className: 'pfb pfb-content pfb--timeline pfb--dense pfb--local pfb-content--guide',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'content-pillar',
    blockType: 'content',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'pillar',
    className: 'pfb pfb-content pfb--compact pfb--compact pfb--technical pfb-content--pillar',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'content-story-local',
    blockType: 'content',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'story',
    className: 'pfb pfb-content pfb--contrast pfb--balanced pfb--trust pfb-content--story-local',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'content-diagnostic',
    blockType: 'content',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'diagnostic',
    className: 'pfb pfb-content pfb--magazine pfb--deep pfb--premium pfb-content--diagnostic',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'content-commercial',
    blockType: 'content',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'commercial',
    className: 'pfb pfb-content pfb--masonry pfb--dense pfb--practical pfb-content--commercial',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'content-informational',
    blockType: 'content',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'informational',
    className: 'pfb pfb-content pfb--rail pfb--compact pfb--urgent pfb-content--informational',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'content-urgent-note',
    blockType: 'content',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'urgent',
    className: 'pfb pfb-content pfb--matrix pfb--balanced pfb--local pfb-content--urgent-note',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'content-checklist',
    blockType: 'content',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'checklist',
    className: 'pfb pfb-content pfb--accordion pfb--deep pfb--technical pfb-content--checklist',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'content-deep-dive',
    blockType: 'content',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'deep',
    className: 'pfb pfb-content pfb--spotlight pfb--dense pfb--trust pfb-content--deep-dive',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'content-myths',
    blockType: 'content',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'myths',
    className: 'pfb pfb-content pfb--editorial pfb--compact pfb--premium pfb-content--myths',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'content-mistakes',
    blockType: 'content',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'mistakes',
    className: 'pfb pfb-content pfb--cards pfb--balanced pfb--practical pfb-content--mistakes',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'content-materials',
    blockType: 'content',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'materials',
    className: 'pfb pfb-content pfb--split pfb--deep pfb--urgent pfb-content--materials',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'content-maintenance',
    blockType: 'content',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'maintenance',
    className: 'pfb pfb-content pfb--timeline pfb--dense pfb--local pfb-content--maintenance',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'content-seasonal',
    blockType: 'content',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'seasonal',
    className: 'pfb pfb-content pfb--compact pfb--compact pfb--technical pfb-content--seasonal',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'content-decision-guide',
    blockType: 'content',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'decision',
    className: 'pfb pfb-content pfb--contrast pfb--balanced pfb--trust pfb-content--decision-guide',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
