import type { LayoutRecipe } from './types.js';

export const CtaPanel_RECIPES: LayoutRecipe[] = [
  {
    id: 'ctaPanel-panel',
    blockType: 'ctaPanel',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'panel',
    className: 'pfb pfb-ctaPanel pfb--editorial pfb--compact pfb--premium pfb-ctaPanel--panel',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'ctaPanel-minimal',
    blockType: 'ctaPanel',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'minimal',
    className: 'pfb pfb-ctaPanel pfb--cards pfb--balanced pfb--practical pfb-ctaPanel--minimal',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'ctaPanel-split-contact',
    blockType: 'ctaPanel',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'split',
    className: 'pfb pfb-ctaPanel pfb--split pfb--deep pfb--urgent pfb-ctaPanel--split-contact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'ctaPanel-urgent-contact',
    blockType: 'ctaPanel',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'urgent',
    className: 'pfb pfb-ctaPanel pfb--timeline pfb--dense pfb--local pfb-ctaPanel--urgent-contact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'ctaPanel-soft-cta',
    blockType: 'ctaPanel',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'soft',
    className: 'pfb pfb-ctaPanel pfb--compact pfb--compact pfb--technical pfb-ctaPanel--soft-cta',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'ctaPanel-form-first',
    blockType: 'ctaPanel',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'form',
    className: 'pfb pfb-ctaPanel pfb--contrast pfb--balanced pfb--trust pfb-ctaPanel--form-first',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'ctaPanel-phone-first',
    blockType: 'ctaPanel',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'phone',
    className: 'pfb pfb-ctaPanel pfb--magazine pfb--deep pfb--premium pfb-ctaPanel--phone-first',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'ctaPanel-whatsapp-style',
    blockType: 'ctaPanel',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'whatsapp',
    className: 'pfb pfb-ctaPanel pfb--masonry pfb--dense pfb--practical pfb-ctaPanel--whatsapp-style',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'ctaPanel-diagnostic-cta',
    blockType: 'ctaPanel',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'diagnostic',
    className: 'pfb pfb-ctaPanel pfb--rail pfb--compact pfb--urgent pfb-ctaPanel--diagnostic-cta',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'ctaPanel-quote-cta',
    blockType: 'ctaPanel',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'quote',
    className: 'pfb pfb-ctaPanel pfb--matrix pfb--balanced pfb--local pfb-ctaPanel--quote-cta',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'ctaPanel-inspection-cta',
    blockType: 'ctaPanel',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'inspection',
    className: 'pfb pfb-ctaPanel pfb--accordion pfb--deep pfb--technical pfb-ctaPanel--inspection-cta',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'ctaPanel-premium-consult',
    blockType: 'ctaPanel',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'premium',
    className: 'pfb pfb-ctaPanel pfb--spotlight pfb--dense pfb--trust pfb-ctaPanel--premium-consult',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'ctaPanel-neighborhood-cta',
    blockType: 'ctaPanel',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'neighborhood',
    className: 'pfb pfb-ctaPanel pfb--editorial pfb--compact pfb--premium pfb-ctaPanel--neighborhood-cta',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'ctaPanel-after-hours',
    blockType: 'ctaPanel',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'after',
    className: 'pfb pfb-ctaPanel pfb--cards pfb--balanced pfb--practical pfb-ctaPanel--after-hours',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'ctaPanel-photo-request',
    blockType: 'ctaPanel',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'photo',
    className: 'pfb pfb-ctaPanel pfb--split pfb--deep pfb--urgent pfb-ctaPanel--photo-request',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'ctaPanel-two-paths',
    blockType: 'ctaPanel',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'two',
    className: 'pfb pfb-ctaPanel pfb--timeline pfb--dense pfb--local pfb-ctaPanel--two-paths',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'ctaPanel-sticky-style',
    blockType: 'ctaPanel',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'sticky',
    className: 'pfb pfb-ctaPanel pfb--compact pfb--compact pfb--technical pfb-ctaPanel--sticky-style',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'ctaPanel-final-close',
    blockType: 'ctaPanel',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'final',
    className: 'pfb pfb-ctaPanel pfb--contrast pfb--balanced pfb--trust pfb-ctaPanel--final-close',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
