import type { LayoutRecipe } from './types.js';

export const Faq_RECIPES: LayoutRecipe[] = [
  {
    id: 'faq-columns',
    blockType: 'faq',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'columns',
    className: 'pfb pfb-faq pfb--editorial pfb--compact pfb--premium pfb-faq--columns',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'faq-editorial',
    blockType: 'faq',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'editorial',
    className: 'pfb pfb-faq pfb--cards pfb--balanced pfb--practical pfb-faq--editorial',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'faq-accordion-rich',
    blockType: 'faq',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'accordion',
    className: 'pfb pfb-faq pfb--split pfb--deep pfb--urgent pfb-faq--accordion-rich',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'faq-compact',
    blockType: 'faq',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'compact',
    className: 'pfb pfb-faq pfb--timeline pfb--dense pfb--local pfb-faq--compact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'faq-local-faq',
    blockType: 'faq',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'local',
    className: 'pfb pfb-faq pfb--compact pfb--compact pfb--technical pfb-faq--local-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'faq-urgent-faq',
    blockType: 'faq',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'urgent',
    className: 'pfb pfb-faq pfb--contrast pfb--balanced pfb--trust pfb-faq--urgent-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'faq-pricing-faq',
    blockType: 'faq',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'pricing',
    className: 'pfb pfb-faq pfb--magazine pfb--deep pfb--premium pfb-faq--pricing-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'faq-trust-faq',
    blockType: 'faq',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'trust',
    className: 'pfb pfb-faq pfb--masonry pfb--dense pfb--practical pfb-faq--trust-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'faq-technical-faq',
    blockType: 'faq',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'technical',
    className: 'pfb pfb-faq pfb--rail pfb--compact pfb--urgent pfb-faq--technical-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'faq-objection-faq',
    blockType: 'faq',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'objection',
    className: 'pfb pfb-faq pfb--matrix pfb--balanced pfb--local pfb-faq--objection-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'faq-neighborhood-faq',
    blockType: 'faq',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'neighborhood',
    className: 'pfb pfb-faq pfb--accordion pfb--deep pfb--technical pfb-faq--neighborhood-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'faq-comparison-faq',
    blockType: 'faq',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'comparison',
    className: 'pfb pfb-faq pfb--spotlight pfb--dense pfb--trust pfb-faq--comparison-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'faq-aftercare-faq',
    blockType: 'faq',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'aftercare',
    className: 'pfb pfb-faq pfb--editorial pfb--compact pfb--premium pfb-faq--aftercare-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'faq-materials-faq',
    blockType: 'faq',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'materials',
    className: 'pfb pfb-faq pfb--cards pfb--balanced pfb--practical pfb-faq--materials-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'faq-diagnostic-faq',
    blockType: 'faq',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'diagnostic',
    className: 'pfb pfb-faq pfb--split pfb--deep pfb--urgent pfb-faq--diagnostic-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'faq-warranty-faq',
    blockType: 'faq',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'warranty',
    className: 'pfb pfb-faq pfb--timeline pfb--dense pfb--local pfb-faq--warranty-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'faq-safety-faq',
    blockType: 'faq',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'safety',
    className: 'pfb pfb-faq pfb--compact pfb--compact pfb--technical pfb-faq--safety-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'faq-seasonal-faq',
    blockType: 'faq',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'seasonal',
    className: 'pfb pfb-faq pfb--contrast pfb--balanced pfb--trust pfb-faq--seasonal-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
