import type { LayoutRecipe } from './types.js';

export const Hero_RECIPES: LayoutRecipe[] = [
  {
    id: 'hero-split-proof',
    blockType: 'hero',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'split',
    className: 'pfb pfb-hero pfb--editorial pfb--compact pfb--premium pfb-hero--split-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'hero-editorial-local',
    blockType: 'hero',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'editorial',
    className: 'pfb pfb-hero pfb--cards pfb--balanced pfb--practical pfb-hero--editorial-local',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'hero-contrast-action',
    blockType: 'hero',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'contrast',
    className: 'pfb pfb-hero pfb--split pfb--deep pfb--urgent pfb-hero--contrast-action',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'hero-full-impact',
    blockType: 'hero',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'full',
    className: 'pfb pfb-hero pfb--timeline pfb--dense pfb--local pfb-hero--full-impact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'hero-neighborhood-focus',
    blockType: 'hero',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'neighborhood',
    className: 'pfb pfb-hero pfb--compact pfb--compact pfb--technical pfb-hero--neighborhood-focus',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'hero-premium-minimal',
    blockType: 'hero',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'premium',
    className: 'pfb pfb-hero pfb--contrast pfb--balanced pfb--trust pfb-hero--premium-minimal',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'hero-urgent-strip',
    blockType: 'hero',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'urgent',
    className: 'pfb pfb-hero pfb--magazine pfb--deep pfb--premium pfb-hero--urgent-strip',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'hero-proof-stack',
    blockType: 'hero',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'proof',
    className: 'pfb pfb-hero pfb--masonry pfb--dense pfb--practical pfb-hero--proof-stack',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'hero-authority-sidebar',
    blockType: 'hero',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'authority',
    className: 'pfb pfb-hero pfb--rail pfb--compact pfb--urgent pfb-hero--authority-sidebar',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'hero-cinematic-local',
    blockType: 'hero',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'cinematic',
    className: 'pfb pfb-hero pfb--matrix pfb--balanced pfb--local pfb-hero--cinematic-local',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'hero-two-cta',
    blockType: 'hero',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'two',
    className: 'pfb pfb-hero pfb--accordion pfb--deep pfb--technical pfb-hero--two-cta',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'hero-diagnostic-first',
    blockType: 'hero',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'diagnostic',
    className: 'pfb pfb-hero pfb--spotlight pfb--dense pfb--trust pfb-hero--diagnostic-first',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'hero-service-chooser',
    blockType: 'hero',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'service',
    className: 'pfb pfb-hero pfb--editorial pfb--compact pfb--premium pfb-hero--service-chooser',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'hero-trust-led',
    blockType: 'hero',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'trust',
    className: 'pfb pfb-hero pfb--cards pfb--balanced pfb--practical pfb-hero--trust-led',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'hero-map-led',
    blockType: 'hero',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'map',
    className: 'pfb pfb-hero pfb--split pfb--deep pfb--urgent pfb-hero--map-led',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'hero-problem-solution',
    blockType: 'hero',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'problem',
    className: 'pfb pfb-hero pfb--timeline pfb--dense pfb--local pfb-hero--problem-solution',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'hero-before-after',
    blockType: 'hero',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'before',
    className: 'pfb pfb-hero pfb--compact pfb--compact pfb--technical pfb-hero--before-after',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'hero-compact-above-fold',
    blockType: 'hero',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'compact',
    className: 'pfb pfb-hero pfb--contrast pfb--balanced pfb--trust pfb-hero--compact-above-fold',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
