import type { LayoutRecipe } from './types.js';

export const LocalProof_RECIPES: LayoutRecipe[] = [
  {
    id: 'localProof-local',
    blockType: 'localProof',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'local',
    className: 'pfb pfb-localProof pfb--editorial pfb--compact pfb--premium pfb-localProof--local',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'localProof-cards',
    blockType: 'localProof',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'cards',
    className: 'pfb pfb-localProof pfb--cards pfb--balanced pfb--practical pfb-localProof--cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'localProof-neighborhood-proof',
    blockType: 'localProof',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'neighborhood',
    className: 'pfb pfb-localProof pfb--split pfb--deep pfb--urgent pfb-localProof--neighborhood-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'localProof-route-proof',
    blockType: 'localProof',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'route',
    className: 'pfb pfb-localProof pfb--timeline pfb--dense pfb--local pfb-localProof--route-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'localProof-building-type-proof',
    blockType: 'localProof',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'building',
    className: 'pfb pfb-localProof pfb--compact pfb--compact pfb--technical pfb-localProof--building-type-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'localProof-climate-proof',
    blockType: 'localProof',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'climate',
    className: 'pfb pfb-localProof pfb--contrast pfb--balanced pfb--trust pfb-localProof--climate-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'localProof-access-proof',
    blockType: 'localProof',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'access',
    className: 'pfb pfb-localProof pfb--magazine pfb--deep pfb--premium pfb-localProof--access-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'localProof-old-town-proof',
    blockType: 'localProof',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'old',
    className: 'pfb pfb-localProof pfb--masonry pfb--dense pfb--practical pfb-localProof--old-town-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'localProof-residential-proof',
    blockType: 'localProof',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'residential',
    className: 'pfb pfb-localProof pfb--rail pfb--compact pfb--urgent pfb-localProof--residential-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'localProof-premium-area-proof',
    blockType: 'localProof',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'premium',
    className: 'pfb pfb-localProof pfb--matrix pfb--balanced pfb--local pfb-localProof--premium-area-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'localProof-industrial-proof',
    blockType: 'localProof',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'industrial',
    className: 'pfb pfb-localProof pfb--accordion pfb--deep pfb--technical pfb-localProof--industrial-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'localProof-coastal-proof',
    blockType: 'localProof',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'coastal',
    className: 'pfb pfb-localProof pfb--spotlight pfb--dense pfb--trust pfb-localProof--coastal-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'localProof-capital-proof',
    blockType: 'localProof',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'capital',
    className: 'pfb pfb-localProof pfb--editorial pfb--compact pfb--premium pfb-localProof--capital-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'localProof-small-town-proof',
    blockType: 'localProof',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'small',
    className: 'pfb pfb-localProof pfb--cards pfb--balanced pfb--practical pfb-localProof--small-town-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'localProof-map-note',
    blockType: 'localProof',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'map',
    className: 'pfb pfb-localProof pfb--split pfb--deep pfb--urgent pfb-localProof--map-note',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'localProof-local-objections',
    blockType: 'localProof',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'local',
    className: 'pfb pfb-localProof pfb--timeline pfb--dense pfb--local pfb-localProof--local-objections',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'localProof-local-materials',
    blockType: 'localProof',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'local',
    className: 'pfb pfb-localProof pfb--compact pfb--compact pfb--technical pfb-localProof--local-materials',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'localProof-seasonal-proof',
    blockType: 'localProof',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'seasonal',
    className: 'pfb pfb-localProof pfb--contrast pfb--balanced pfb--trust pfb-localProof--seasonal-proof',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
