import type { LayoutRecipe } from './types.js';

export const Map_RECIPES: LayoutRecipe[] = [
  {
    id: 'map-local-note',
    blockType: 'map',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'local',
    className: 'pfb pfb-map pfb--editorial pfb--compact pfb--premium pfb-map--local-note',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'map-split',
    blockType: 'map',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'split',
    className: 'pfb pfb-map pfb--cards pfb--balanced pfb--practical pfb-map--split',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'map-coverage-cards',
    blockType: 'map',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'coverage',
    className: 'pfb pfb-map pfb--split pfb--deep pfb--urgent pfb-map--coverage-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'map-neighborhood-list',
    blockType: 'map',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'neighborhood',
    className: 'pfb pfb-map pfb--timeline pfb--dense pfb--local pfb-map--neighborhood-list',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'map-route-style',
    blockType: 'map',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'route',
    className: 'pfb pfb-map pfb--compact pfb--compact pfb--technical pfb-map--route-style',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'map-nearby-areas',
    blockType: 'map',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'nearby',
    className: 'pfb pfb-map pfb--contrast pfb--balanced pfb--trust pfb-map--nearby-areas',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'map-zone-clusters',
    blockType: 'map',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'zone',
    className: 'pfb pfb-map pfb--magazine pfb--deep pfb--premium pfb-map--zone-clusters',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'map-service-radius',
    blockType: 'map',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'service',
    className: 'pfb pfb-map pfb--masonry pfb--dense pfb--practical pfb-map--service-radius',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'map-capital-map',
    blockType: 'map',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'capital',
    className: 'pfb pfb-map pfb--rail pfb--compact pfb--urgent pfb-map--capital-map',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'map-coastal-map',
    blockType: 'map',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'coastal',
    className: 'pfb pfb-map pfb--matrix pfb--balanced pfb--local pfb-map--coastal-map',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'map-industrial-map',
    blockType: 'map',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'industrial',
    className: 'pfb pfb-map pfb--accordion pfb--deep pfb--technical pfb-map--industrial-map',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'map-residential-map',
    blockType: 'map',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'residential',
    className: 'pfb pfb-map pfb--spotlight pfb--dense pfb--trust pfb-map--residential-map',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'map-old-town-map',
    blockType: 'map',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'old',
    className: 'pfb pfb-map pfb--editorial pfb--compact pfb--premium pfb-map--old-town-map',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'map-premium-zone-map',
    blockType: 'map',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'premium',
    className: 'pfb pfb-map pfb--cards pfb--balanced pfb--practical pfb-map--premium-zone-map',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'map-small-town-map',
    blockType: 'map',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'small',
    className: 'pfb pfb-map pfb--split pfb--deep pfb--urgent pfb-map--small-town-map',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'map-access-map',
    blockType: 'map',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'access',
    className: 'pfb pfb-map pfb--timeline pfb--dense pfb--local pfb-map--access-map',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'map-arrival-context',
    blockType: 'map',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'arrival',
    className: 'pfb pfb-map pfb--compact pfb--compact pfb--technical pfb-map--arrival-context',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'map-geo-faq',
    blockType: 'map',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'geo',
    className: 'pfb pfb-map pfb--contrast pfb--balanced pfb--trust pfb-map--geo-faq',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
