import type { LayoutRecipe } from './types.js';

export const PriceGuidance_RECIPES: LayoutRecipe[] = [
  {
    id: 'priceGuidance-split',
    blockType: 'priceGuidance',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'split',
    className: 'pfb pfb-priceGuidance pfb--editorial pfb--compact pfb--premium pfb-priceGuidance--split',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'priceGuidance-compact',
    blockType: 'priceGuidance',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'compact',
    className: 'pfb pfb-priceGuidance pfb--cards pfb--balanced pfb--practical pfb-priceGuidance--compact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'priceGuidance-factor-cards',
    blockType: 'priceGuidance',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'factor',
    className: 'pfb pfb-priceGuidance pfb--split pfb--deep pfb--urgent pfb-priceGuidance--factor-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'priceGuidance-range-explainer',
    blockType: 'priceGuidance',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'range',
    className: 'pfb pfb-priceGuidance pfb--timeline pfb--dense pfb--local pfb-priceGuidance--range-explainer',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'priceGuidance-budget-checklist',
    blockType: 'priceGuidance',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'budget',
    className: 'pfb pfb-priceGuidance pfb--compact pfb--compact pfb--technical pfb-priceGuidance--budget-checklist',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'priceGuidance-transparent-note',
    blockType: 'priceGuidance',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'transparent',
    className: 'pfb pfb-priceGuidance pfb--contrast pfb--balanced pfb--trust pfb-priceGuidance--transparent-note',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'priceGuidance-commercial-comparison',
    blockType: 'priceGuidance',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'commercial',
    className: 'pfb pfb-priceGuidance pfb--magazine pfb--deep pfb--premium pfb-priceGuidance--commercial-comparison',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'priceGuidance-premium-breakdown',
    blockType: 'priceGuidance',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'premium',
    className: 'pfb pfb-priceGuidance pfb--masonry pfb--dense pfb--practical pfb-priceGuidance--premium-breakdown',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'priceGuidance-urgency-impact',
    blockType: 'priceGuidance',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'urgency',
    className: 'pfb pfb-priceGuidance pfb--rail pfb--compact pfb--urgent pfb-priceGuidance--urgency-impact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'priceGuidance-material-impact',
    blockType: 'priceGuidance',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'material',
    className: 'pfb pfb-priceGuidance pfb--matrix pfb--balanced pfb--local pfb-priceGuidance--material-impact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'priceGuidance-access-impact',
    blockType: 'priceGuidance',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'access',
    className: 'pfb pfb-priceGuidance pfb--accordion pfb--deep pfb--technical pfb-priceGuidance--access-impact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'priceGuidance-local-impact',
    blockType: 'priceGuidance',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'local',
    className: 'pfb pfb-priceGuidance pfb--spotlight pfb--dense pfb--trust pfb-priceGuidance--local-impact',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'priceGuidance-table-light',
    blockType: 'priceGuidance',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'table',
    className: 'pfb pfb-priceGuidance pfb--editorial pfb--compact pfb--premium pfb-priceGuidance--table-light',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'priceGuidance-quote-builder',
    blockType: 'priceGuidance',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'quote',
    className: 'pfb pfb-priceGuidance pfb--cards pfb--balanced pfb--practical pfb-priceGuidance--quote-builder',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'priceGuidance-what-includes',
    blockType: 'priceGuidance',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'what',
    className: 'pfb pfb-priceGuidance pfb--split pfb--deep pfb--urgent pfb-priceGuidance--what-includes',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'priceGuidance-avoid-surprises',
    blockType: 'priceGuidance',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'avoid',
    className: 'pfb pfb-priceGuidance pfb--timeline pfb--dense pfb--local pfb-priceGuidance--avoid-surprises',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'priceGuidance-tiered-context',
    blockType: 'priceGuidance',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'tiered',
    className: 'pfb pfb-priceGuidance pfb--compact pfb--compact pfb--technical pfb-priceGuidance--tiered-context',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'priceGuidance-faq-price',
    blockType: 'priceGuidance',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'faq',
    className: 'pfb pfb-priceGuidance pfb--contrast pfb--balanced pfb--trust pfb-priceGuidance--faq-price',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
