import type { LayoutRecipe } from './types.js';

export const ProcessSteps_RECIPES: LayoutRecipe[] = [
  {
    id: 'processSteps-timeline',
    blockType: 'processSteps',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'timeline',
    className: 'pfb pfb-processSteps pfb--editorial pfb--compact pfb--premium pfb-processSteps--timeline',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'processSteps-cards',
    blockType: 'processSteps',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'cards',
    className: 'pfb pfb-processSteps pfb--cards pfb--balanced pfb--practical pfb-processSteps--cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'processSteps-numbered-rail',
    blockType: 'processSteps',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'numbered',
    className: 'pfb pfb-processSteps pfb--split pfb--deep pfb--urgent pfb-processSteps--numbered-rail',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'processSteps-split-steps',
    blockType: 'processSteps',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'split',
    className: 'pfb pfb-processSteps pfb--timeline pfb--dense pfb--local pfb-processSteps--split-steps',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'processSteps-compact-steps',
    blockType: 'processSteps',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'compact',
    className: 'pfb pfb-processSteps pfb--compact pfb--compact pfb--technical pfb-processSteps--compact-steps',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'processSteps-diagnostic-flow',
    blockType: 'processSteps',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'diagnostic',
    className: 'pfb pfb-processSteps pfb--contrast pfb--balanced pfb--trust pfb-processSteps--diagnostic-flow',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'processSteps-urgent-flow',
    blockType: 'processSteps',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'urgent',
    className: 'pfb pfb-processSteps pfb--magazine pfb--deep pfb--premium pfb-processSteps--urgent-flow',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'processSteps-quality-flow',
    blockType: 'processSteps',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'quality',
    className: 'pfb pfb-processSteps pfb--masonry pfb--dense pfb--practical pfb-processSteps--quality-flow',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'processSteps-before-during-after',
    blockType: 'processSteps',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'before',
    className: 'pfb pfb-processSteps pfb--rail pfb--compact pfb--urgent pfb-processSteps--before-during-after',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'processSteps-checklist-flow',
    blockType: 'processSteps',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'checklist',
    className: 'pfb pfb-processSteps pfb--matrix pfb--balanced pfb--local pfb-processSteps--checklist-flow',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'processSteps-accordion-flow',
    blockType: 'processSteps',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'accordion',
    className: 'pfb pfb-processSteps pfb--accordion pfb--deep pfb--technical pfb-processSteps--accordion-flow',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'processSteps-local-route',
    blockType: 'processSteps',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'local',
    className: 'pfb pfb-processSteps pfb--spotlight pfb--dense pfb--trust pfb-processSteps--local-route',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'processSteps-premium-method',
    blockType: 'processSteps',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'premium',
    className: 'pfb pfb-processSteps pfb--editorial pfb--compact pfb--premium pfb-processSteps--premium-method',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'processSteps-risk-first',
    blockType: 'processSteps',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'risk',
    className: 'pfb pfb-processSteps pfb--cards pfb--balanced pfb--practical pfb-processSteps--risk-first',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'processSteps-photo-first',
    blockType: 'processSteps',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'photo',
    className: 'pfb pfb-processSteps pfb--split pfb--deep pfb--urgent pfb-processSteps--photo-first',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'processSteps-budget-first',
    blockType: 'processSteps',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'budget',
    className: 'pfb pfb-processSteps pfb--timeline pfb--dense pfb--local pfb-processSteps--budget-first',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'processSteps-maintenance-flow',
    blockType: 'processSteps',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'maintenance',
    className: 'pfb pfb-processSteps pfb--compact pfb--compact pfb--technical pfb-processSteps--maintenance-flow',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'processSteps-aftercare-flow',
    blockType: 'processSteps',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'aftercare',
    className: 'pfb pfb-processSteps pfb--contrast pfb--balanced pfb--trust pfb-processSteps--aftercare-flow',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
