import type { LayoutRecipe } from './types.js';

export const ServicesGrid_RECIPES: LayoutRecipe[] = [
  {
    id: 'servicesGrid-cards-3',
    blockType: 'servicesGrid',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'cards',
    className: 'pfb pfb-servicesGrid pfb--editorial pfb--compact pfb--premium pfb-servicesGrid--cards-3',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'servicesGrid-cards-4',
    blockType: 'servicesGrid',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'cards',
    className: 'pfb pfb-servicesGrid pfb--cards pfb--balanced pfb--practical pfb-servicesGrid--cards-4',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'servicesGrid-masonry',
    blockType: 'servicesGrid',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'masonry',
    className: 'pfb pfb-servicesGrid pfb--split pfb--deep pfb--urgent pfb-servicesGrid--masonry',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'servicesGrid-editorial-list',
    blockType: 'servicesGrid',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'editorial',
    className: 'pfb pfb-servicesGrid pfb--timeline pfb--dense pfb--local pfb-servicesGrid--editorial-list',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'servicesGrid-icon-grid',
    blockType: 'servicesGrid',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'icon',
    className: 'pfb pfb-servicesGrid pfb--compact pfb--compact pfb--technical pfb-servicesGrid--icon-grid',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'servicesGrid-problem-grid',
    blockType: 'servicesGrid',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'problem',
    className: 'pfb pfb-servicesGrid pfb--contrast pfb--balanced pfb--trust pfb-servicesGrid--problem-grid',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'servicesGrid-neighborhood-grid',
    blockType: 'servicesGrid',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'neighborhood',
    className: 'pfb pfb-servicesGrid pfb--magazine pfb--deep pfb--premium pfb-servicesGrid--neighborhood-grid',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'servicesGrid-premium-tiles',
    blockType: 'servicesGrid',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'premium',
    className: 'pfb pfb-servicesGrid pfb--masonry pfb--dense pfb--practical pfb-servicesGrid--premium-tiles',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'servicesGrid-compact-list',
    blockType: 'servicesGrid',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'compact',
    className: 'pfb pfb-servicesGrid pfb--rail pfb--compact pfb--urgent pfb-servicesGrid--compact-list',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'servicesGrid-comparison-cards',
    blockType: 'servicesGrid',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'comparison',
    className: 'pfb pfb-servicesGrid pfb--matrix pfb--balanced pfb--local pfb-servicesGrid--comparison-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'servicesGrid-use-case-cards',
    blockType: 'servicesGrid',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'use',
    className: 'pfb pfb-servicesGrid pfb--accordion pfb--deep pfb--technical pfb-servicesGrid--use-case-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'servicesGrid-diagnostic-cards',
    blockType: 'servicesGrid',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'diagnostic',
    className: 'pfb pfb-servicesGrid pfb--spotlight pfb--dense pfb--trust pfb-servicesGrid--diagnostic-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'servicesGrid-material-cards',
    blockType: 'servicesGrid',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'material',
    className: 'pfb pfb-servicesGrid pfb--editorial pfb--compact pfb--premium pfb-servicesGrid--material-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'servicesGrid-urgency-cards',
    blockType: 'servicesGrid',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'urgency',
    className: 'pfb pfb-servicesGrid pfb--cards pfb--balanced pfb--practical pfb-servicesGrid--urgency-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'servicesGrid-proof-cards',
    blockType: 'servicesGrid',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'proof',
    className: 'pfb pfb-servicesGrid pfb--split pfb--deep pfb--urgent pfb-servicesGrid--proof-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'servicesGrid-pricing-aware',
    blockType: 'servicesGrid',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'pricing',
    className: 'pfb pfb-servicesGrid pfb--timeline pfb--dense pfb--local pfb-servicesGrid--pricing-aware',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'servicesGrid-seasonal-services',
    blockType: 'servicesGrid',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'seasonal',
    className: 'pfb pfb-servicesGrid pfb--compact pfb--compact pfb--technical pfb-servicesGrid--seasonal-services',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'servicesGrid-local-clusters',
    blockType: 'servicesGrid',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'local',
    className: 'pfb pfb-servicesGrid pfb--contrast pfb--balanced pfb--trust pfb-servicesGrid--local-clusters',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
