import type { LayoutRecipe } from './types.js';

export const TrustBand_RECIPES: LayoutRecipe[] = [
  {
    id: 'trustBand-band',
    blockType: 'trustBand',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'band',
    className: 'pfb pfb-trustBand pfb--editorial pfb--compact pfb--premium pfb-trustBand--band',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'trustBand-contrast',
    blockType: 'trustBand',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'contrast',
    className: 'pfb pfb-trustBand pfb--cards pfb--balanced pfb--practical pfb-trustBand--contrast',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'trustBand-logos-style',
    blockType: 'trustBand',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'logos',
    className: 'pfb pfb-trustBand pfb--split pfb--deep pfb--urgent pfb-trustBand--logos-style',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'trustBand-proof-cards',
    blockType: 'trustBand',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'proof',
    className: 'pfb pfb-trustBand pfb--timeline pfb--dense pfb--local pfb-trustBand--proof-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'trustBand-guarantee-strip',
    blockType: 'trustBand',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'guarantee',
    className: 'pfb pfb-trustBand pfb--compact pfb--compact pfb--technical pfb-trustBand--guarantee-strip',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'trustBand-review-logic',
    blockType: 'trustBand',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'review',
    className: 'pfb pfb-trustBand pfb--contrast pfb--balanced pfb--trust pfb-trustBand--review-logic',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'trustBand-safety-strip',
    blockType: 'trustBand',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'safety',
    className: 'pfb pfb-trustBand pfb--magazine pfb--deep pfb--premium pfb-trustBand--safety-strip',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'trustBand-compliance-band',
    blockType: 'trustBand',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'compliance',
    className: 'pfb pfb-trustBand pfb--masonry pfb--dense pfb--practical pfb-trustBand--compliance-band',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'trustBand-before-after-trust',
    blockType: 'trustBand',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'before',
    className: 'pfb pfb-trustBand pfb--rail pfb--compact pfb--urgent pfb-trustBand--before-after-trust',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'trustBand-method-trust',
    blockType: 'trustBand',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'method',
    className: 'pfb pfb-trustBand pfb--matrix pfb--balanced pfb--local pfb-trustBand--method-trust',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'trustBand-local-trust',
    blockType: 'trustBand',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'local',
    className: 'pfb pfb-trustBand pfb--accordion pfb--deep pfb--technical pfb-trustBand--local-trust',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'trustBand-materials-trust',
    blockType: 'trustBand',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'materials',
    className: 'pfb pfb-trustBand pfb--spotlight pfb--dense pfb--trust pfb-trustBand--materials-trust',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'trustBand-team-trust',
    blockType: 'trustBand',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'team',
    className: 'pfb pfb-trustBand pfb--editorial pfb--compact pfb--premium pfb-trustBand--team-trust',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'trustBand-response-trust',
    blockType: 'trustBand',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'response',
    className: 'pfb pfb-trustBand pfb--cards pfb--balanced pfb--practical pfb-trustBand--response-trust',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'trustBand-quality-points',
    blockType: 'trustBand',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'quality',
    className: 'pfb pfb-trustBand pfb--split pfb--deep pfb--urgent pfb-trustBand--quality-points',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'trustBand-risk-reduction',
    blockType: 'trustBand',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'risk',
    className: 'pfb pfb-trustBand pfb--timeline pfb--dense pfb--local pfb-trustBand--risk-reduction',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'trustBand-verification-grid',
    blockType: 'trustBand',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'verification',
    className: 'pfb pfb-trustBand pfb--compact pfb--compact pfb--technical pfb-trustBand--verification-grid',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'trustBand-minimal-seals',
    blockType: 'trustBand',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'minimal',
    className: 'pfb pfb-trustBand pfb--contrast pfb--balanced pfb--trust pfb-trustBand--minimal-seals',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
