import type { LayoutRecipe } from './types.js';

export const UrgencyPanel_RECIPES: LayoutRecipe[] = [
  {
    id: 'urgencyPanel-checklist',
    blockType: 'urgencyPanel',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'checklist',
    className: 'pfb pfb-urgencyPanel pfb--editorial pfb--compact pfb--premium pfb-urgencyPanel--checklist',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'urgencyPanel-cards',
    blockType: 'urgencyPanel',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'cards',
    className: 'pfb pfb-urgencyPanel pfb--cards pfb--balanced pfb--practical pfb-urgencyPanel--cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'urgencyPanel-risk-strip',
    blockType: 'urgencyPanel',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'risk',
    className: 'pfb pfb-urgencyPanel pfb--split pfb--deep pfb--urgent pfb-urgencyPanel--risk-strip',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'urgencyPanel-emergency-steps',
    blockType: 'urgencyPanel',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'emergency',
    className: 'pfb pfb-urgencyPanel pfb--timeline pfb--dense pfb--local pfb-urgencyPanel--emergency-steps',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'urgencyPanel-red-flags',
    blockType: 'urgencyPanel',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'red',
    className: 'pfb pfb-urgencyPanel pfb--compact pfb--compact pfb--technical pfb-urgencyPanel--red-flags',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'urgencyPanel-decision-tree',
    blockType: 'urgencyPanel',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'decision',
    className: 'pfb pfb-urgencyPanel pfb--contrast pfb--balanced pfb--trust pfb-urgencyPanel--decision-tree',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
  {
    id: 'urgencyPanel-call-now',
    blockType: 'urgencyPanel',
    shell: 'magazine',
    rendererKey: 'cta',
    density: 'deep',
    tone: 'premium',
    family: 'call',
    className: 'pfb pfb-urgencyPanel pfb--magazine pfb--deep pfb--premium pfb-urgencyPanel--call-now',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-deep',
  },
  {
    id: 'urgencyPanel-damage-control',
    blockType: 'urgencyPanel',
    shell: 'masonry',
    rendererKey: 'table',
    density: 'dense',
    tone: 'practical',
    family: 'damage',
    className: 'pfb pfb-urgencyPanel pfb--masonry pfb--dense pfb--practical pfb-urgencyPanel--damage-control',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-dense',
  },
  {
    id: 'urgencyPanel-safety-first',
    blockType: 'urgencyPanel',
    shell: 'rail',
    rendererKey: 'map',
    density: 'compact',
    tone: 'urgent',
    family: 'safety',
    className: 'pfb pfb-urgencyPanel pfb--rail pfb--compact pfb--urgent pfb-urgencyPanel--safety-first',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-compact',
  },
  {
    id: 'urgencyPanel-timeline-urgent',
    blockType: 'urgencyPanel',
    shell: 'matrix',
    rendererKey: 'editorial',
    density: 'balanced',
    tone: 'local',
    family: 'timeline',
    className: 'pfb pfb-urgencyPanel pfb--matrix pfb--balanced pfb--local pfb-urgencyPanel--timeline-urgent',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-balanced',
  },
  {
    id: 'urgencyPanel-triage-cards',
    blockType: 'urgencyPanel',
    shell: 'accordion',
    rendererKey: 'checklist',
    density: 'deep',
    tone: 'technical',
    family: 'triage',
    className: 'pfb pfb-urgencyPanel pfb--accordion pfb--deep pfb--technical pfb-urgencyPanel--triage-cards',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-deep',
  },
  {
    id: 'urgencyPanel-do-dont',
    blockType: 'urgencyPanel',
    shell: 'spotlight',
    rendererKey: 'matrix',
    density: 'dense',
    tone: 'trust',
    family: 'do',
    className: 'pfb pfb-urgencyPanel pfb--spotlight pfb--dense pfb--trust pfb-urgencyPanel--do-dont',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-dense',
  },
  {
    id: 'urgencyPanel-availability-note',
    blockType: 'urgencyPanel',
    shell: 'editorial',
    rendererKey: 'hero',
    density: 'compact',
    tone: 'premium',
    family: 'availability',
    className: 'pfb pfb-urgencyPanel pfb--editorial pfb--compact pfb--premium pfb-urgencyPanel--availability-note',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'premium-compact',
  },
  {
    id: 'urgencyPanel-night-weekend',
    blockType: 'urgencyPanel',
    shell: 'cards',
    rendererKey: 'cards',
    density: 'balanced',
    tone: 'practical',
    family: 'night',
    className: 'pfb pfb-urgencyPanel pfb--cards pfb--balanced pfb--practical pfb-urgencyPanel--night-weekend',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'practical-balanced',
  },
  {
    id: 'urgencyPanel-pre-arrival',
    blockType: 'urgencyPanel',
    shell: 'split',
    rendererKey: 'steps',
    density: 'deep',
    tone: 'urgent',
    family: 'pre',
    className: 'pfb pfb-urgencyPanel pfb--split pfb--deep pfb--urgent pfb-urgencyPanel--pre-arrival',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'urgent-deep',
  },
  {
    id: 'urgencyPanel-fast-diagnosis',
    blockType: 'urgencyPanel',
    shell: 'timeline',
    rendererKey: 'faq',
    density: 'dense',
    tone: 'local',
    family: 'fast',
    className: 'pfb pfb-urgencyPanel pfb--timeline pfb--dense pfb--local pfb-urgencyPanel--fast-diagnosis',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'local-dense',
  },
  {
    id: 'urgencyPanel-priority-levels',
    blockType: 'urgencyPanel',
    shell: 'compact',
    rendererKey: 'split',
    density: 'compact',
    tone: 'technical',
    family: 'priority',
    className: 'pfb pfb-urgencyPanel pfb--compact pfb--compact pfb--technical pfb-urgencyPanel--priority-levels',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'technical-compact',
  },
  {
    id: 'urgencyPanel-calm-guidance',
    blockType: 'urgencyPanel',
    shell: 'contrast',
    rendererKey: 'band',
    density: 'balanced',
    tone: 'trust',
    family: 'calm',
    className: 'pfb pfb-urgencyPanel pfb--contrast pfb--balanced pfb--trust pfb-urgencyPanel--calm-guidance',
    slots: ['kicker', 'heading', 'lead', 'primary', 'secondary', 'cta'],
    contentStrategy: 'trust-balanced',
  },
];
